## RNN(Recurrent Neural Network) : 순환 신경망
#### 순서가 있는 시퀀스 데이터, time series data(시계열 데이터)를 입력하여 예측

In [1]:
import tensorflow as tf
import numpy as np

### One cell: 4 (input_dim) in 2 (hidden_size)

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [8]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]],dtype=np.float32)

hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=hidden_size,return_sequences=True,
                               return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))    # (N,T,D)
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) # (N,T,H)
print('states: {}, shape: {}'.format(states, states.shape))    # (N,H)
# N: batch_size, T:sequennce length, D:input dimensize, H:hidden size

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.6304771 -0.3963635]]], shape: (1, 1, 2)
states: [[-0.6304771 -0.3963635]], shape: (1, 2)


### Unfolding to n sequences

![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [18]:
# One cell RNN input_dim (4) -> output_dim (2), sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=2,return_sequences=True,return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))    # (N,T,D)
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) # (N,T,H)
print('states: {}, shape: {}'.format(states, states.shape))    # (N,H)

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[-0.5066132   0.07082766]
  [ 0.48055744 -0.28198925]
  [ 0.21016887 -0.16778585]
  [ 0.3134839   0.10195331]
  [-0.64495736 -0.7188344 ]]], shape: (1, 5, 2)
states: [[-0.64495736 -0.7188344 ]], shape: (1, 2)


### Batching input

![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [21]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2

rnn = tf.keras.layers.SimpleRNN(units=2,return_sequences=True,return_state=True)
outputs,states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))    # (N,T,D) (3,5,4)
print('outputs: {}, shape: {}'.format(outputs, outputs.shape)) # (N,T,H) (3,5,2)
print('states: {}, shape: {}'.format(states, states.shape))    # (N,H) , (3,2) 

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)
outputs: [[[-0.06402092 -0.22160055]
  [ 0.65745926  0.42197907]
  [-0.7950697   0.7534866 ]
  [ 0.36258206  0.8489928 ]
  [-0.7869265   0.14176713]]

 [[ 0.6251782   0.5876971 ]
  [-0.87080854 -0.10714716]
  [ 0.3970806   0.3709428 ]
  [-0.678863    0.7255583 ]
  [ 0.2567256   0.8424061 ]]

 [[-0.41818798  0.48716995]
  [-0.0076473   0.7624009 ]
  [ 0.6483339   0.8928053 ]
  [ 0.12174145  0.9205812 ]
  [-0.48485947  0.8970973 ]]], shape: (3, 5, 2)
states: [[-0.7869265   0.14176713]
 [ 0.2567256   0.8424061 ]
 [-0.48485947  0.8970973 ]], shape: (3, 2)
