In [1]:
# XOR : 1 layer
# 2진 분류 : Logistic Regression
# 활성화 함수 : sigmoid 함수 사용
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]

y_data = [[0],
          [1],
          [1],
          [0]]

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
# 변수 초기화 : weight, bias
# (4,2) * (2,1) = (4,1)
W = tf.Variable(tf.random.normal([2,1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

In [4]:
# 예측 함수(hypothesis) : H(X) = sigmoid(X*W + B)
def hypothesis(X):
    return tf.sigmoid(tf.matmul(X,W) + b)  # 0과 1사이의 값이 출력

In [5]:
# 비용 함수 : logloss, 2진분류모델
def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) +
                          (1 - y_train)*tf.math.log(1-hypothesis(x_train)))
    return cost

In [6]:
# 경사 하강법
# learning_rate(학습율)을 0.01 로 설정하여 optimizer객체를 생성
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [7]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10001):
    optimizer.minimize(cost_func,var_list=[W,b])
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W:',W.numpy(),' b:',b.numpy())
print('***** Learning Finished!!') 

***** Start Learning!!
0000 cost:[ 0.7333478 ]  W: [[-0.170307 ]
 [-0.9402863]]  b: [0.23652855]
1000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
2000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
3000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
4000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
5000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
6000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
7000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
8000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
9000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
10000 cost:[ 0.6931472 ]  W: [[-4.898185e-08]
 [ 3.608348e-08]]  b: [-6.0882535e-08]
***** Learning Finished!!


In [8]:
# weight과 bias 출력
print('Weight:',W.numpy())
print('Bias:',b.numpy())

Weight: [[-4.898185e-08]
 [ 3.608348e-08]]
Bias: [-6.0882535e-08]


In [9]:
# 평가 : 정확도(accuracy)
def predict(X):
    return tf.cast(hypothesis(X) > 0.5 ,dtype=tf.float32)

# 학습 데이터를 그대로 검증 데이터로 사용하여 예측한 경우
x_test = x_train
y_test = y_train

# 예측
preds = predict(x_test)   
print(preds)

# 정확도
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test),dtype=tf.float32))
print('Accuracy:',accuracy.numpy())
print('Hypothesis:\n',hypothesis(x_test).numpy())
print('Predict:\n',preds.numpy())  # Accuracy: 0.5

# 1층(단층) 신경망으로 XOR Problem 해결 불가

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
Accuracy: 0.5
Hypothesis:
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
Predict:
 [[0.]
 [0.]
 [0.]
 [0.]]
